name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.MASSBOOKING_SITE_SERVER }}
          username: ${{ secrets.MASSBOOKING_SITE_USER }}
          password: ${{ secrets.MASSBOOKING_SITE_PASS }}
          server-dir: /api.reginapaciscc.org/
          
      - name: Install Dependencies, Run migration and build
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: source /home/regilwdi/nodevenv/api.reginapaciscc.org/20/bin/activate && 
                    cd /home/regilwdi/api.reginapaciscc.org
                    npm run migrate:deploy
          host: ${{ secrets.MASSBOOKING_SITE_SERVER }}
          username: ${{ secrets.MASSBOOKING_SITE_USER }}
          password: ${{ secrets.MASSBOOKING_SITE_PASS }}
          port: ${{ secrets.MASSBOOKING_SITE_PORT }}